apiVersion: v1
kind: Secret
metadata:
  name: grafana-tls
  namespace: grafana
type: kubernetes.io/tls
data:
  tls.crt: coloque o conteúdo do certificado aqui
  tls.key: coloque o conteúdo da chave aqui
